train_dataset: "/data/physionet/dataset/train"
val_dataset: "/data/physionet/dataset/val"
test_dataset: "/data/physionet/dataset/test"
summary_writer: "/out/tensorboard"
model_name: "/out/test_model"
