splits_yaml: local.yaml
model_yaml: DresdenDeepSleep.yaml

# paths
folder_dir: ../challenge-2018/training
output_path: out
summary_writer: "tensorboard"
# ------------

# training params
device: cpu
epochs: 2
train_batch_size: 1
test_batch_size: 1
num_workers: 4
scheduler: none
# ------------

# testing only locally.
split: validation
idx: 0
arousals_to_visualise:
  # - "obst"
  # - "cent"
  # - "mix"
  # - "hypo"
  - "rera"
  # - "wake"
  # - "nrem1"
  # - "nrem2"
  # - "nrem3"
  # - "rem"
# ------------

# testing params
test_csv_name: "outputs.csv"
# ------------

