# paths
folder_dir: /data/physionet/challenge-2018/training
output_path: /out
summary_writer: "/out/tensorboard"
model_name: "/out/best_model.pt"
ref555_file_path: /data/physionet/ref555.npy
# ------------


# DeepSleep:
# smoothing: 1e-7
# max_lr: 1e-4
# weight_decay: 1e-5
# beta_1: 0.9
# beta_2: 0.999

# SleepNet:
# smoothing: 0
# max_lr: 1e-3
# weight_decay: 0
# beta_1: 0.9
# beta_2: 0.999

# training params
device: cuda
epochs: 200
train_batch_size: 1
test_batch_size: 1
pos_weight: 10.0
max_lr: 1e-4
weight_decay: 1e-5
beta_1: 0.9
beta_2: 0.999
warmstart_percentage: 0.05
num_workers: 8
smoothing: 1e-7 # deepsleep paper: 1e-7. better: 1e-1
randomize_padding: False
# ------------

# other
num_channels: 12
reduction_factor: 50
summary_shape: "(1, 1_260_000, 12)"
# summary_shape: "(1, 1048576, 13)"
# ------------

# testing only locally.
split: validation
idx: 0
# ------------
