splits_yaml: stratified.yaml
model_yaml: DeepSleep.yaml

# paths
folder_dir: /data/physionet/challenge-2018/training
output_path: /out
summary_writer: "/out/tensorboard"
model_name: "/out/best_model.pt"
# ------------

# training params
device: cuda
epochs: 200
train_batch_size: 2
test_batch_size: 1
num_workers: 8
scheduler: none
optimizer: adamw
# ------------

# testing only locally.
# split: validation
# idx: 0
# ------------
